Trigger on BASELINE** tags.

diff --git a/.github/workflows/speech-test-data-ci.yml b/.github/workflows/speech-test-data-ci.yml
--- a/.github/workflows/speech-test-data-ci.yml
+++ b/.github/workflows/speech-test-data-ci.yml
@@ -14,17 +14,17 @@ on:
     # Execute on pushes to master.
     # branches:
     #   - master
-    # # The push must include updates to testing data.
-    # paths:
-    #   # The path from the root of the repository to a .zip with .wav files and a
-    #   # .txt transcript used for testing.
-    #   - "testing/audio-and-trans.zip"
-    # tags:
-    #   # The workflow may be triggered with or without changes to testing data by
-    #   # pushing a tag starting with `BASELINE`, like `BASELINE000`. To push a
-    #   # tag, run `git tag -a <<TAG_NAME>>` then `git push origin <<TAG_NAME>>`.
-    #   - BASELINE
-    #   - BASELINE**
+    # The push must include updates to testing data.
+    paths:
+      # The path from the root of the repository to a .zip with .wav files and a
+      # .txt transcript used for testing.
+      - "testing/audio-and-trans.zip"
+    tags:
+      # The workflow may be triggered with or without changes to testing data by
+      # pushing a tag starting with `BASELINE`, like `BASELINE000`. To push a
+      # tag, run `git tag -a <<TAG>>` then `git push origin <<TAG>>`.
+      - BASELINE
+      - BASELINE**
 
 env:
   # V2 Custom Speech models can be either "Acoustic" or "Language" models. The
@@ -104,20 +104,26 @@ jobs:
       - name: Upload audio and human transcript testing data
         run: |
           unzip ${{ env.TEST_ZIP_SOURCE_PATH }} -d ${{ env.TEST_BUILD_FOLDER_PATH }}
-      #     zip -r ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_AUDIO_ZIP_FILE }} ${{ env.TEST_BUILD_FOLDER_PATH }} -x "*.txt"
-      #     speech dataset create -n audio_trans_test_${{ env.CURRENT_COMMIT_HASH }} -a ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_AUDIO_ZIP_FILE }} -t ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_TRANS_FILE }} --wait > ${{ env.TEST_BUILD_FOLDER_PATH }}/audio-trans-test-upload.txt
-      #     audio_trans_test_id=$(cat ${{ env.TEST_BUILD_FOLDER_PATH }}/audio-trans-test-upload.txt | sed -n '3p')
-      #     if ! [[ ${audio_trans_test_id//-/} =~ ^[[:xdigit:]]{32}$ ]]
-      #     then
-      #       echo "::error ::Failed to upload audio and human-labeled transcript testing data. Check that the correct paths are defined in environment variables or re-run all jobs."
-      #       exit 1
-      #     fi
-      #     echo "::set-env name=AUDIO_TRANS_TEST_ID::$(echo $audio_trans_test_id)"
+          zip -r ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_AUDIO_ZIP_FILE }} ${{ env.TEST_BUILD_FOLDER_PATH }} -x "*.txt"
+          speech dataset create -n audio_trans_test_${{ env.CURRENT_COMMIT_HASH }} -a ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_AUDIO_ZIP_FILE }} -t ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_TRANS_FILE }} --wait > ${{ env.TEST_BUILD_FOLDER_PATH }}/audio-trans-test-upload.txt
+          audio_trans_test_id=$(cat ${{ env.TEST_BUILD_FOLDER_PATH }}/audio-trans-test-upload.txt | sed -n '3p')
+          if ! [[ ${audio_trans_test_id//-/} =~ ^[[:xdigit:]]{32}$ ]]
+          then
+            echo "::error ::Failed to upload audio and human-labeled transcript testing data. Check that the correct paths are defined in environment variables or re-run all jobs."
+            exit 1
+          fi
+          echo "::set-env name=AUDIO_TRANS_TEST_ID::$(echo $audio_trans_test_id)"
 
-      # Get the benchmark Speech model. Fail if a GUID is not generated.
-      # `CUSTOM_SPEECH_MODEL_KIND` will be used to filter results from the
-      # `speech model list` command to get the benchmark Speech model.
-      - name: Get the benchmark Speech model
+      # Filter results from the `speech model list` command by the
+      # CUSTOM_SPEECH_MODEL_KIND, which must be a language or an acoustic model.
+      # Get the latest benchmark model if it exists. If a benchmark model does
+      # not exist, simply use the latest baseline model.
+      #
+      # Check that the benchmark and baseline models have been successfully
+      # downloaded with [[${my_variable//-/} =~ ^[[:xdigit:]]{32}$]] which will
+      # return true if the variable is a valid GUID with 32 hexadecimal
+      # characters.
+      - name: Get the benchmark or baseline model
         run: |
           speech model list > ${{ env.TEST_BUILD_FOLDER_PATH }}/speech-model-list.txt
           sed -i "/${{ env.CUSTOM_SPEECH_MODEL_KIND }}/!d" ${{ env.TEST_BUILD_FOLDER_PATH }}/speech-model-list.txt
@@ -130,7 +136,8 @@ jobs:
               echo "::error ::Failed to get the latest baseline model. Possibly re-run all jobs."
               exit 1
             fi
-            echo "::set-env name=BASE_MODEL_ID::$(echo $base_model_id)"
+            echo "::set-env name=MODEL_ID::$(echo $base_model_id)"
+            echo "::set-env name=TEST_NAME_INFIX::baseline_tag"
           else
             custom_speech_model_id=$(cat ${{ env.TEST_BUILD_FOLDER_PATH }}/speech-model-list.txt | tail -1 | awk '{print $1;}')
             if ! [[ ${custom_speech_model_id//-/} =~ ^[[:xdigit:]]{32}$ ]]
@@ -138,10 +145,77 @@ jobs:
               echo "::error ::Failed to get the benchmark Custom Speech model. Possibly re-run all jobs."
               exit 1
             fi
-            echo "::set-env name=CUSTOM_SPEECH_MODEL_ID::$(echo $custom_speech_model_id)"
+            echo "::set-env name=MODEL_ID::$(echo $custom_speech_model_id)"
+            echo "::set-env name=TEST_NAME_INFIX::test_data_update"
           fi
 
-      - name: echo
+      # Test with Speech.
+      #
+      # Check that the test has been successfully created with
+      # [[${my_variable//-/} =~ ^[[:xdigit:]]{32}$]] which will return true if
+      # the variable is a valid GUID with 32 hexadecimal characters.
+      - name: Test the benchmark Speech model
         run: |
-          echo cs id ${{ env.CUSTOM_SPEECH_MODEL_ID }}
-          echo base id ${{ env.BASE_MODEL_ID }}
+          speech test create -n test_from_test_data_update_${{ env.CURRENT_COMMIT_HASH }} -a ${{ env.AUDIO_TRANS_TEST_ID }} -m ${{ env.MODEL_ID }} -lm ${{ env.MODEL_ID }} --wait > ${{ env.TEST_BUILD_FOLDER_PATH }}/test-output.txt
+          test_id=$(cat ${{ env.TEST_BUILD_FOLDER_PATH }}/test-output.txt | sed -n '3p')
+          if ! [[ ${test_id//-/} =~ ^[[:xdigit:]]{32}$ ]]
+          then
+            echo "::error ::Failed to test the Custom Speech model. Possibly re-run all jobs."
+            exit 1
+          fi
+          echo "::set-env name=TEST_ID::$(echo $test_id)"
+
+      # Get the content from the test and remove the first line, which is
+      # logging, so the result is a JSON file.
+      - name: Store JSON test output
+        run: |
+          test_summary_file_name="test-summary-from-test-data-update-${{ env.CURRENT_COMMIT_HASH }}.json"
+          echo "::set-env name=TEST_SUMMARY_FILE::$(echo $test_summary_file_name)"
+          speech test show ${{ env.TEST_ID }} > ${{ env.TEST_BUILD_FOLDER_PATH }}/$test_summary_file_name
+          sed -i '1d' ${{ env.TEST_BUILD_FOLDER_PATH }}/$test_summary_file_name
+
+      # It is not necessary to check if AUDIO_TRANS_TEST_ID is a valid GUID
+      # because the workflow will have already failed if not.
+      - name: Delete testing datasets
+        run: |
+          speech dataset delete ${{ env.AUDIO_TRANS_TEST_ID }}
+          echo DELETED AUDIO+HUMAN-LABELED TRANSCRIPT TESTING DATA.
+
+      #########################################################################
+      # Archive test summary and test results in Blob
+      #########################################################################
+
+      # https://github.com/Azure/azure-cli
+      - name: Azure Login
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Save test summary in Azure Blob
+        uses: azure/CLI@v1
+        with:
+          inlineScript: az storage blob upload --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --container-name test-results --name ${{ env.TEST_SUMMARY_FILE }} --file ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_SUMMARY_FILE }} --auth-mode login
+
+      - name: Save test results in Azure Blob
+        run: |
+          results_url=$(jq '.resultsUrl' ${{ env.TEST_BUILD_FOLDER_PATH }}/${{ env.TEST_SUMMARY_FILE }} | xargs)
+          curl $results_url -o "test-results.txt"
+          az storage blob upload --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --container-name test-results --name test-results-from-test-data-update-${{ env.CURRENT_COMMIT_HASH }}.txt --file test-results.txt --auth-mode login
+
+      - name: Update benchmark in configuration file
+        run: |
+          echo ${{ env.TEST_SUMMARY_FILE }} > ${{ env.TEST_BUILD_FOLDER_PATH }}/benchmark-test.txt
+          az storage blob upload --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --container-name configuration --name benchmark-test.txt --file ${{ env.TEST_BUILD_FOLDER_PATH }}/benchmark-test.txt --auth-mode login
+
+      # Set environment variables to be bash variables to avoid substitution
+      # errors. Check that the test has been successfully uploaded with
+      # [[${my_variable//-/} =~ ^[[:xdigit:]]{32}$]] which will return true if
+      # the variable is a valid GUID with 32 hexadecimal characters.
+      - name: Delete test
+        run: |
+          test_id=${{ env.TEST_ID }}
+          if [[ ${test_id//-/} =~ ^[[:xdigit:]]{32}$ ]]
+          then
+            speech test delete ${{ env.TEST_ID }}
+            echo DELETED TEST.
+          fi
